POST http://localhost/subject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYwLCJpYXQiOjE3MTMzMjM0ODEsImV4cCI6MTcxMzMyNDM4MX0.lzvRBiX65aL1W_XvIcNBMhnU9HC1ciGY3yDQVmOMYVM
Content-Type: application/json

{
    "category_name": "Theology",
    "name": "si",
    "description": "si"
}