POST http://localhost/subject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgyLCJpYXQiOjE3MTM1ODIyOTAsImV4cCI6MTcxMzU4MzE5MH0.h5RKe97Kzz_qaPzRnsfmoZ7rh5pldz54DbTY5fzQtyk
Content-Type: application/json

{
    "category_name": "Theology",
    "name": "si",
    "description": "si",
    "price": 10,
    "days": [
        {
            "name": "Monday",
            "timeslots": [
                {
                    "start_time": "10:00",
                    "end_time": "11:00"
                },
                {
                    "start_time": "15:00",
                    "end_time": "17:00"
                }
            ]
        },
        {
            "name": "Tuesday",
            "timeslots": [
                {
                    "start_time": "18:00",
                    "end_time": "19:00"
                }
            ]
        }
    ]
}