POST http://movieweb.mediaversetv.com/subject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYwLCJpYXQiOjE3MTMzNjAyMTUsImV4cCI6MTcxMzM2MTExNX0.i55kCvkxpMyAV-8RyKUjdvoH4WyEYZ-dupSqtaa4u2k
Content-Type: application/json

{
    "category_name": "Theology",
    "name": "si",
    "description": "si"
}