POST http://localhost/reservation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY2LCJpYXQiOjE3MTYyOTMzNTIsImV4cCI6MTcxNjI5NDI1Mn0.0F3DFNStNAqL3HO2uff4yKPXNq_zwJHYpF9zacHz_B0

{
    "timeslot_id": 1,
    "date": "2024-5-27"
}